import {
  School,
  Branch,
  AcademicYear,
  EducationalLevel,
  ExamType,
  UserRole,
  PassingGradeConfig,
  QuestionType,
  TestType,
  WeightConfig,
  QuestionItem,
  ExamEvent,
  EventQuestionAssignment,
  Participant,
  Staff,
  EventRegistration,
  ExamResultRecord,
  PermissionNode,
  RoleConfig,
  AppConfig,
} from '@/types';

export const mockBranches: Branch[] = [
  {
    id: 'br-1',
    code: 'CAB-JKT-01',
    name: 'Cabang Wilayah I DKI Jakarta',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    manager: 'Drs. Bambang Haryadi, M.Pd.',
    phone: '021-7890123',
    schoolCount: 14,
    status: 'active',
  },
  {
    id: 'br-2',
    code: 'CAB-JBR-02',
    name: 'Cabang Wilayah II Jawa Barat',
    city: 'Bandung',
    province: 'Jawa Barat',
    manager: 'Dr. Hj. Siti Nurjanah, M.Si.',
    phone: '022-4567890',
    schoolCount: 18,
    status: 'active',
  },
  {
    id: 'br-3',
    code: 'CAB-JTG-03',
    name: 'Cabang Wilayah III Jawa Tengah',
    city: 'Semarang',
    province: 'Jawa Tengah',
    manager: 'Ir. Sutrisno, M.Kom.',
    phone: '024-8901234',
    schoolCount: 12,
    status: 'active',
  },
];

export const mockSchools: School[] = [
  {
    id: 'sch-1',
    name: 'SMA Negeri 1 Jakarta',
    npsn: '20101456',
    branchId: 'br-1',
    branchName: 'Cabang Wilayah I DKI Jakarta',
    levelId: 'lvl-3',
    levelName: 'SMA',
    address: 'Jl. Budi Utomo No. 7, Pasar Baru, Jakarta Pusat',
    phone: '021-3865001',
    principal: 'Dra. Endang Sulastri, M.Ed.',
    status: 'active',
    createdAt: '2024-01-10',
  },
  {
    id: 'sch-2',
    name: 'SMK Teknologi Industri 1 Bandung',
    npsn: '20219842',
    branchId: 'br-2',
    branchName: 'Cabang Wilayah II Jawa Barat',
    levelId: 'lvl-4',
    levelName: 'SMK',
    address: 'Jl. Soekarno Hatta No. 450, Bandung',
    phone: '022-7564120',
    principal: 'Drs. Asep Sunandar, M.T.',
    status: 'active',
    createdAt: '2024-01-12',
  },
  {
    id: 'sch-3',
    name: 'SMP Negeri 2 Semarang',
    npsn: '20305612',
    branchId: 'br-3',
    branchName: 'Cabang Wilayah III Jawa Tengah',
    levelId: 'lvl-2',
    levelName: 'SMP',
    address: 'Jl. Pemuda No. 112, Semarang',
    phone: '024-3512990',
    principal: 'H. Suwarto, S.Pd., M.Pd.',
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'sch-4',
    name: 'SMA Swasta Garuda Mandiri',
    npsn: '20108923',
    branchId: 'br-1',
    branchName: 'Cabang Wilayah I DKI Jakarta',
    levelId: 'lvl-3',
    levelName: 'SMA',
    address: 'Jl. Fatmawati Raya Kav. 18, Jakarta Selatan',
    phone: '021-7692211',
    principal: 'Agus Purnomo, S.Si.',
    status: 'active',
    createdAt: '2024-02-01',
  },
];

export const mockAcademicYears: AcademicYear[] = [
  {
    id: 'ay-1',
    year: '2024/2025',
    semester: 'Ganjil',
    startDate: '2024-07-15',
    endDate: '2024-12-20',
    isActive: false,
  },
  {
    id: 'ay-2',
    year: '2024/2025',
    semester: 'Genap',
    startDate: '2025-01-06',
    endDate: '2025-06-25',
    isActive: true,
  },
  {
    id: 'ay-3',
    year: '2025/2026',
    semester: 'Ganjil',
    startDate: '2025-07-14',
    endDate: '2025-12-19',
    isActive: false,
  },
];

export const mockEducationalLevels: EducationalLevel[] = [
  { id: 'lvl-1', code: 'SD', name: 'Sekolah Dasar / Madrasah Ibtidaiyah', description: 'Tingkat pendidikan dasar 6 tahun', defaultPassingGrade: 70 },
  { id: 'lvl-2', code: 'SMP', name: 'Sekolah Menengah Pertama', description: 'Tingkat pendidikan menengah pertama 3 tahun', defaultPassingGrade: 75 },
  { id: 'lvl-3', code: 'SMA', name: 'Sekolah Menengah Atas', description: 'Tingkat pendidikan menengah atas peminatan', defaultPassingGrade: 78 },
  { id: 'lvl-4', code: 'SMK', name: 'Sekolah Menengah Kejuruan', description: 'Tingkat pendidikan vokasi dan kejuruan', defaultPassingGrade: 80 },
];

export const mockExamTypes: ExamType[] = [
  { id: 'et-1', code: 'PTS', name: 'Penilaian Tengah Semester', category: 'Formatif', description: 'Evaluasi berkala pertengahan semester' },
  { id: 'et-2', code: 'PAS', name: 'Penilaian Akhir Semester', category: 'Sumatif', description: 'Evaluasi komprehensif akhir periode akademik' },
  { id: 'et-3', code: 'UTBK', name: 'Simulasi Seleksi Masuk PTN / UTBK', category: 'Seleksi', description: 'Simulasi format tes potensi skolastik dan literasi' },
  { id: 'et-4', code: 'US', name: 'Ujian Sekolah Standar Daerah', category: 'Sumatif', description: 'Ujian kelulusan akhir jenjang sekolah' },
];

export const mockUserRoles: UserRole[] = [
  { id: 'role-1', code: 'SUPER_ADMIN', name: 'Super Administrator', description: 'Akses penuh ke seluruh sistem, master data, dan RBAC', userCount: 3, isSystem: true },
  { id: 'role-2', code: 'ADMIN_CABANG', name: 'Administrator Cabang', description: 'Mengelola sekolah dan event di tingkat kantor cabang', userCount: 8, isSystem: false },
  { id: 'role-3', code: 'ADMIN_SEKOLAH', name: 'Operator / Admin Sekolah', description: 'Mengelola data peserta, staf, dan pendaftaran sekolah', userCount: 35, isSystem: false },
  { id: 'role-4', code: 'GURU_PANITIA', name: 'Guru & Panitia Ujian', description: 'Menginput bank soal, mapping soal event, dan melihat nilai', userCount: 120, isSystem: false },
];

export const mockPassingGrades: PassingGradeConfig[] = [
  { id: 'pg-1', subject: 'Matematika Wajib', levelId: 'lvl-3', levelName: 'SMA', minimumScore: 75, maximumScore: 100, remedialThreshold: 65 },
  { id: 'pg-2', subject: 'Bahasa Indonesia', levelId: 'lvl-3', levelName: 'SMA', minimumScore: 78, maximumScore: 100, remedialThreshold: 70 },
  { id: 'pg-3', subject: 'Fisika Terapan', levelId: 'lvl-4', levelName: 'SMK', minimumScore: 80, maximumScore: 100, remedialThreshold: 72 },
  { id: 'pg-4', subject: 'Ilmu Pengetahuan Alam', levelId: 'lvl-2', levelName: 'SMP', minimumScore: 75, maximumScore: 100, remedialThreshold: 68 },
];

export const mockQuestionTypes: QuestionType[] = [
  { id: 'qt-1', code: 'PG', name: 'Pilihan Ganda (Single Choice)', description: 'Pilihan opsi A hingga E dengan satu kunci jawaban mutlak', hasOptions: true, isAutoGraded: true },
  { id: 'qt-2', code: 'ESAI', name: 'Uraian / Esai Terbuka', description: 'Jawaban teks bebas dengan rubrik penilaian acuan guru', hasOptions: false, isAutoGraded: false },
];

export const mockTestTypes: TestType[] = [
  { id: 'tt-1', code: 'AKADEMIK', name: 'Tes Kompetensi Akademik (TKA)', purpose: 'Mengukur penguasaan materi kurikulum mata pelajaran', scoringModel: 'Standard 0-100' },
  { id: 'tt-2', code: 'PSIKOTES', name: 'Tes Bakat & Minat Skolastik (TPS)', purpose: 'Mengukur potensi kognitif dan penalaran logika', scoringModel: 'IRT / Bobot Dinamis' },
  { id: 'tt-3', code: 'KEPRIBADIAN', name: 'Survei Karakter & Profil Pelajar', purpose: 'Asesmen non-kognitif integritas dan kerjasama', scoringModel: 'Skala 1-5' },
];

export const mockWeightConfigs: WeightConfig[] = [
  { id: 'wc-1', examTypeId: 'et-2', examTypeName: 'Penilaian Akhir Semester (PAS)', multipleChoiceWeight: 70, essayWeight: 30, penaltyWrongAnswer: 0, scorePerQuestion: 2.5 },
  { id: 'wc-2', examTypeId: 'et-3', examTypeName: 'Simulasi Seleksi Masuk PTN / UTBK', multipleChoiceWeight: 100, essayWeight: 0, penaltyWrongAnswer: -1, scorePerQuestion: 4.0 },
  { id: 'wc-3', examTypeId: 'et-1', examTypeName: 'Penilaian Tengah Semester (PTS)', multipleChoiceWeight: 60, essayWeight: 40, penaltyWrongAnswer: 0, scorePerQuestion: 3.0 },
];

export const mockStaff: Staff[] = [
  { id: 'stf-1', nip: '198204152006041002', fullName: 'Drs. Hendro Wibowo', role: 'Guru & Koordinator Ujian', schoolId: 'sch-1', schoolName: 'SMA Negeri 1 Jakarta', subjectSpecialization: 'Matematika', email: 'hendro.wibowo@sman1jkt.sch.id', phone: '081234567890', status: 'active' },
  { id: 'stf-2', nip: '198709232010012015', fullName: 'Rina Kartika, S.Pd., M.Hum.', role: 'Guru Penyusun Soal', schoolId: 'sch-1', schoolName: 'SMA Negeri 1 Jakarta', subjectSpecialization: 'Bahasa Indonesia', email: 'rina.kartika@sman1jkt.sch.id', phone: '081398765432', status: 'active' },
  { id: 'stf-3', nip: '197903112005011008', fullName: 'Budi Santoso, S.T., M.Kom.', role: 'Operator CBT & Teknisi Lab', schoolId: 'sch-2', schoolName: 'SMK Teknologi Industri 1 Bandung', subjectSpecialization: 'Teknik Komputer & Jaringan', email: 'budi.santoso@smkti1bdg.sch.id', phone: '085712348765', status: 'active' },
  { id: 'stf-4', nip: '199102142015032009', fullName: 'Dewi Anggraini, S.Si.', role: 'Guru Pengampu', schoolId: 'sch-3', schoolName: 'SMP Negeri 2 Semarang', subjectSpecialization: 'Fisika & IPA', email: 'dewi.anggraini@smpn2smg.sch.id', phone: '082199887766', status: 'active' },
  { id: 'stf-5', nip: '198511202008041003', fullName: 'Rahmat Hidayat, S.Pd.', role: 'Pengawas Ujian', schoolId: 'sch-4', schoolName: 'SMA Swasta Garuda Mandiri', subjectSpecialization: 'Biologi', email: 'rahmat.h@garudamandiri.sch.id', phone: '081177665544', status: 'active' },
];

export const mockParticipants: Participant[] = [
  { id: 'par-1', nisn: '0061234567', fullName: 'Ahmad Faiz Fadhlurrahman', gender: 'L', schoolId: 'sch-1', schoolName: 'SMA Negeri 1 Jakarta', className: 'XII MIPA 1', email: 'faiz.ahmad@student.sman1jkt.sch.id', status: 'active', registeredEventsCount: 3 },
  { id: 'par-2', nisn: '0067654321', fullName: 'Nabila Syakira Putri', gender: 'P', schoolId: 'sch-1', schoolName: 'SMA Negeri 1 Jakarta', className: 'XII MIPA 1', email: 'nabila.putri@student.sman1jkt.sch.id', status: 'active', registeredEventsCount: 3 },
  { id: 'par-3', nisn: '0071982345', fullName: 'Dimas Aditya Pratama', gender: 'L', schoolId: 'sch-2', schoolName: 'SMK Teknologi Industri 1 Bandung', className: 'XI TKJ 2', email: 'dimas.pratama@student.smkti1bdg.sch.id', status: 'active', registeredEventsCount: 2 },
  { id: 'par-4', nisn: '0079876543', fullName: 'Clarissa Maharani Dewi', gender: 'P', schoolId: 'sch-2', schoolName: 'SMK Teknologi Industri 1 Bandung', className: 'XI TKJ 2', email: 'clarissa.dewi@student.smkti1bdg.sch.id', status: 'active', registeredEventsCount: 2 },
  { id: 'par-5', nisn: '0081239876', fullName: 'Rifqi Maulana Yusuf', gender: 'L', schoolId: 'sch-3', schoolName: 'SMP Negeri 2 Semarang', className: 'IX A', email: 'rifqi.m@student.smpn2smg.sch.id', status: 'active', registeredEventsCount: 1 },
  { id: 'par-6', nisn: '0089871234', fullName: 'Aisyah Putri Azzahra', gender: 'P', schoolId: 'sch-3', schoolName: 'SMP Negeri 2 Semarang', className: 'IX A', email: 'aisyah.p@student.smpn2smg.sch.id', status: 'active', registeredEventsCount: 1 },
  { id: 'par-7', nisn: '0063456789', fullName: 'Kevin Ardiansyah', gender: 'L', schoolId: 'sch-4', schoolName: 'SMA Swasta Garuda Mandiri', className: 'XII IPS 2', email: 'kevin.a@student.garuda.sch.id', status: 'active', registeredEventsCount: 2 },
  { id: 'par-8', nisn: '0068765432', fullName: 'Zahra Larasati', gender: 'P', schoolId: 'sch-4', schoolName: 'SMA Swasta Garuda Mandiri', className: 'XII IPS 2', email: 'zahra.l@student.garuda.sch.id', status: 'inactive', registeredEventsCount: 0 },
];

export const mockQuestions: QuestionItem[] = [
  {
    id: 'qst-1',
    code: 'MAT-XII-001',
    subject: 'Matematika Wajib',
    type: 'PG',
    difficulty: 'Sedang',
    prompt: 'Diketahui kubus ABCD.EFGH dengan panjang rusuk 8 cm. Jarak antara titik C ke bidang diagonal BDHF adalah...',
    options: [
      { key: 'A', text: '4 cm', isCorrect: false },
      { key: 'B', text: '4√2 cm', isCorrect: true },
      { key: 'C', text: '4√3 cm', isCorrect: false },
      { key: 'D', text: '8 cm', isCorrect: false },
      { key: 'E', text: '8√2 cm', isCorrect: false },
    ],
    correctAnswer: 'B',
    defaultPoints: 4,
    tags: ['Dimensi Tiga', 'Geometri Ruang'],
    createdAt: '2024-03-01',
    author: 'Drs. Hendro Wibowo',
  },
  {
    id: 'qst-2',
    code: 'MAT-XII-002',
    subject: 'Matematika Wajib',
    type: 'PG',
    difficulty: 'Sukar',
    prompt: 'Nilai dari limit lim(x -> 0) [(1 - cos 4x) / (x * tan 2x)] adalah...',
    options: [
      { key: 'A', text: '1', isCorrect: false },
      { key: 'B', text: '2', isCorrect: false },
      { key: 'C', text: '4', isCorrect: true },
      { key: 'D', text: '8', isCorrect: false },
      { key: 'E', text: '16', isCorrect: false },
    ],
    correctAnswer: 'C',
    defaultPoints: 4,
    tags: ['Kalkulus', 'Limit Trigonometri'],
    createdAt: '2024-03-02',
    author: 'Drs. Hendro Wibowo',
  },
  {
    id: 'qst-3',
    code: 'BIN-XII-001',
    subject: 'Bahasa Indonesia',
    type: 'PG',
    difficulty: 'Mudah',
    prompt: 'Kalimat berikut yang mengandung kata baku sesuai Pedoman Umum Ejaan Bahasa Indonesia (PUEBI) adalah...',
    options: [
      { key: 'A', text: 'Apotik tersebut menyediakan obat-obatan generik berkualitas.', isCorrect: false },
      { key: 'B', text: 'Analisa data dilakukan setelah seluruh kuesioner terkumpul.', isCorrect: false },
      { key: 'C', text: 'Pemerintah menetapkan standarisasi kurikulum nasional baru.', isCorrect: false },
      { key: 'D', text: 'Sistem pembelajaran daring membutuhkan koordinasi aktif.', isCorrect: true },
      { key: 'E', text: 'Aktifitas ekstrakulikuler ditiadakan sementara selama ujian.', isCorrect: false },
    ],
    correctAnswer: 'D',
    defaultPoints: 3,
    tags: ['Tata Bahasa', 'Kosa Kata Baku'],
    createdAt: '2024-03-05',
    author: 'Rina Kartika, S.Pd.',
  },
  {
    id: 'qst-4',
    code: 'FIS-XI-001',
    subject: 'Fisika Terapan',
    type: 'PG',
    difficulty: 'Sedang',
    prompt: 'Sebuah bola pejal bermassa 2 kg dan berjari-jari 10 cm menggelinding tanpa selip pada bidang miring dengan sudut kemiringan 30°. Percepatan linier bola adalah... (g = 10 m/s²)',
    options: [
      { key: 'A', text: '2,50 m/s²', isCorrect: false },
      { key: 'B', text: '3,57 m/s²', isCorrect: true },
      { key: 'C', text: '5,00 m/s²', isCorrect: false },
      { key: 'D', text: '7,14 m/s²', isCorrect: false },
      { key: 'E', text: '10,0 m/s²', isCorrect: false },
    ],
    correctAnswer: 'B',
    defaultPoints: 4,
    tags: ['Dinamika Rotasi', 'Momen Inersia'],
    createdAt: '2024-03-10',
    author: 'Dewi Anggraini, S.Si.',
  },
  {
    id: 'qst-5',
    code: 'MAT-XII-003',
    subject: 'Matematika Wajib',
    type: 'ESAI',
    difficulty: 'Sukar',
    prompt: 'Sebuah perusahaan manufaktur memproduksi x unit barang dengan biaya total C(x) = 2x² - 40x + 1000 (dalam ratusan ribu rupiah). Tentukan jumlah unit barang yang harus diproduksi agar biaya total minimum, serta hitung biaya minimum tersebut secara rinci!',
    rubric: '1. Pemahaman konsep turunan pertama C\'(x) = 0 (Bobot 30%)\n2. Penentuan titik stasioner x = 10 (Bobot 30%)\n3. Perhitungan substitusi biaya minimum C(10) (Bobot 40%)',
    defaultPoints: 10,
    tags: ['Aplikasi Turunan', 'Optimasi'],
    createdAt: '2024-03-12',
    author: 'Drs. Hendro Wibowo',
  },
  {
    id: 'qst-6',
    code: 'BIN-XII-002',
    subject: 'Bahasa Indonesia',
    type: 'ESAI',
    difficulty: 'Sedang',
    prompt: 'Jelaskan perbedaan struktur dan fungsi antara teks eksposisi dan teks editorial berdasarkan kaidah jurnalistik modern!',
    rubric: '1. Ketepatan definisi struktur tesis, argumentasi, penegasan ulang (Bobot 40%)\n2. Perbedaan opini pribadi vs pandangan redaksional institusi (Bobot 40%)\n3. Kerapian bahasa dan koherensi paragraf (Bobot 20%)',
    defaultPoints: 10,
    tags: ['Analisis Teks', 'Jurnalistik'],
    createdAt: '2024-03-14',
    author: 'Rina Kartika, S.Pd.',
  },
];

export const mockEvents: ExamEvent[] = [
  {
    id: 'ev-1',
    title: 'Penilaian Akhir Semester (PAS) Genap 2024/2025',
    examTypeCode: 'PAS',
    academicYear: '2024/2025',
    startDate: '2025-06-02T08:00',
    endDate: '2025-06-09T16:00',
    durationMinutes: 90,
    token: 'PAS25A',
    status: 'active',
    schoolId: 'sch-1',
    schoolName: 'SMA Negeri 1 Jakarta',
    rules: {
      shuffleQuestions: true,
      shuffleOptions: true,
      allowNavigateBack: true,
      disableRightClick: true,
      showScoreImmediately: false,
      enforceFullscreen: true,
    },
    assignedQuestionCount: 5,
    registeredParticipantCount: 42,
    createdAt: '2025-05-15',
  },
  {
    id: 'ev-2',
    title: 'Simulasi Akbar UTBK SNBT Seri I',
    examTypeCode: 'UTBK',
    academicYear: '2024/2025',
    startDate: '2025-06-15T09:00',
    endDate: '2025-06-15T12:00',
    durationMinutes: 120,
    token: 'SNBT01',
    status: 'draft',
    rules: {
      shuffleQuestions: true,
      shuffleOptions: true,
      allowNavigateBack: false,
      disableRightClick: true,
      showScoreImmediately: true,
      enforceFullscreen: true,
    },
    assignedQuestionCount: 4,
    registeredParticipantCount: 120,
    createdAt: '2025-05-20',
  },
  {
    id: 'ev-3',
    title: 'Ujian Tengah Semester (PTS) Gasal 2024/2025',
    examTypeCode: 'PTS',
    academicYear: '2024/2025',
    startDate: '2024-10-07T08:00',
    endDate: '2024-10-12T15:00',
    durationMinutes: 60,
    token: 'PTS24G',
    status: 'completed',
    schoolId: 'sch-2',
    schoolName: 'SMK Teknologi Industri 1 Bandung',
    rules: {
      shuffleQuestions: false,
      shuffleOptions: true,
      allowNavigateBack: true,
      disableRightClick: false,
      showScoreImmediately: true,
      enforceFullscreen: false,
    },
    assignedQuestionCount: 3,
    registeredParticipantCount: 88,
    createdAt: '2024-09-20',
  },
];

export const mockEventQuestionAssignments: EventQuestionAssignment[] = [
  {
    id: 'eqa-1',
    eventId: 'ev-1',
    questionId: 'qst-1',
    orderNumber: 1,
    questionPrompt: 'Diketahui kubus ABCD.EFGH dengan panjang rusuk 8 cm. Jarak antara titik C ke bidang diagonal BDHF adalah...',
    questionType: 'PG',
    subject: 'Matematika Wajib',
    difficulty: 'Sedang',
  },
  {
    id: 'eqa-2',
    eventId: 'ev-1',
    questionId: 'qst-2',
    orderNumber: 2,
    questionPrompt: 'Nilai dari limit lim(x -> 0) [(1 - cos 4x) / (x * tan 2x)] adalah...',
    questionType: 'PG',
    subject: 'Matematika Wajib',
    difficulty: 'Sukar',
  },
  {
    id: 'eqa-3',
    eventId: 'ev-1',
    questionId: 'qst-3',
    orderNumber: 3,
    questionPrompt: 'Kalimat berikut yang mengandung kata baku sesuai Pedoman Umum Ejaan Bahasa Indonesia (PUEBI) adalah...',
    questionType: 'PG',
    subject: 'Bahasa Indonesia',
    difficulty: 'Mudah',
  },
  {
    id: 'eqa-4',
    eventId: 'ev-1',
    questionId: 'qst-5',
    orderNumber: 4,
    questionPrompt: 'Sebuah perusahaan manufaktur memproduksi x unit barang dengan biaya total C(x) = 2x² - 40x + 1000...',
    questionType: 'ESAI',
    subject: 'Matematika Wajib',
    difficulty: 'Sukar',
  },
  {
    id: 'eqa-5',
    eventId: 'ev-1',
    questionId: 'qst-6',
    orderNumber: 5,
    questionPrompt: 'Jelaskan perbedaan struktur dan fungsi antara teks eksposisi dan teks editorial...',
    questionType: 'ESAI',
    subject: 'Bahasa Indonesia',
    difficulty: 'Sedang',
  },
  // ev-2
  {
    id: 'eqa-6',
    eventId: 'ev-2',
    questionId: 'qst-1',
    orderNumber: 1,
    questionPrompt: 'Diketahui kubus ABCD.EFGH dengan panjang rusuk 8 cm. Jarak antara titik C ke bidang diagonal BDHF adalah...',
    questionType: 'PG',
    subject: 'Matematika Wajib',
    difficulty: 'Sedang',
  },
  {
    id: 'eqa-7',
    eventId: 'ev-2',
    questionId: 'qst-2',
    orderNumber: 2,
    questionPrompt: 'Nilai dari limit lim(x -> 0) [(1 - cos 4x) / (x * tan 2x)] adalah...',
    questionType: 'PG',
    subject: 'Matematika Wajib',
    difficulty: 'Sukar',
  },
  {
    id: 'eqa-8',
    eventId: 'ev-2',
    questionId: 'qst-4',
    orderNumber: 3,
    questionPrompt: 'Sebuah bola pejal bermassa 2 kg dan berjari-jari 10 cm menggelinding tanpa selip...',
    questionType: 'PG',
    subject: 'Fisika Terapan',
    difficulty: 'Sedang',
  },
];

export const mockRegistrations: EventRegistration[] = [
  { id: 'reg-1', eventId: 'ev-1', participantId: 'par-1', registeredAt: '2025-05-18 10:30', attendanceStatus: 'Selesai', score: 88, isPassed: true },
  { id: 'reg-2', eventId: 'ev-1', participantId: 'par-2', registeredAt: '2025-05-18 10:32', attendanceStatus: 'Selesai', score: 94, isPassed: true },
  { id: 'reg-3', eventId: 'ev-1', participantId: 'par-3', registeredAt: '2025-05-19 09:15', attendanceStatus: 'Selesai', score: 68, isPassed: false },
  { id: 'reg-4', eventId: 'ev-1', participantId: 'par-4', registeredAt: '2025-05-19 09:20', attendanceStatus: 'Belum Hadir' },
  { id: 'reg-5', eventId: 'ev-2', participantId: 'par-1', registeredAt: '2025-05-22 14:00', attendanceStatus: 'Belum Hadir' },
  { id: 'reg-6', eventId: 'ev-2', participantId: 'par-7', registeredAt: '2025-05-22 14:10', attendanceStatus: 'Belum Hadir' },
];

export const mockExamResults: ExamResultRecord[] = [
  { id: 'res-1', participantId: 'par-1', participantName: 'Ahmad Faiz Fadhlurrahman', nisn: '0061234567', schoolName: 'SMA Negeri 1 Jakarta', className: 'XII MIPA 1', eventId: 'ev-1', eventTitle: 'Penilaian Akhir Semester (PAS) Genap 2024/2025', rawScore: 88, finalScore: 88, passingScore: 75, status: 'Lulus', completedAt: '2025-06-03 10:15', durationUsedMinutes: 78 },
  { id: 'res-2', participantId: 'par-2', participantName: 'Nabila Syakira Putri', nisn: '0067654321', schoolName: 'SMA Negeri 1 Jakarta', className: 'XII MIPA 1', eventId: 'ev-1', eventTitle: 'Penilaian Akhir Semester (PAS) Genap 2024/2025', rawScore: 94, finalScore: 94, passingScore: 75, status: 'Lulus', completedAt: '2025-06-03 09:58', durationUsedMinutes: 62 },
  { id: 'res-3', participantId: 'par-3', participantName: 'Dimas Aditya Pratama', nisn: '0071982345', schoolName: 'SMK Teknologi Industri 1 Bandung', className: 'XI TKJ 2', eventId: 'ev-1', eventTitle: 'Penilaian Akhir Semester (PAS) Genap 2024/2025', rawScore: 68, finalScore: 68, passingScore: 75, status: 'Tidak Lulus', completedAt: '2025-06-03 10:28', durationUsedMinutes: 88 },
  { id: 'res-4', participantId: 'par-7', participantName: 'Kevin Ardiansyah', nisn: '0063456789', schoolName: 'SMA Swasta Garuda Mandiri', className: 'XII IPS 2', eventId: 'ev-3', eventTitle: 'Ujian Tengah Semester (PTS) Gasal 2024/2025', rawScore: 82, finalScore: 82, passingScore: 75, status: 'Lulus', completedAt: '2024-10-08 09:40', durationUsedMinutes: 52 },
  { id: 'res-5', participantId: 'par-5', participantName: 'Rifqi Maulana Yusuf', nisn: '0081239876', schoolName: 'SMP Negeri 2 Semarang', className: 'IX A', eventId: 'ev-3', eventTitle: 'Ujian Tengah Semester (PTS) Gasal 2024/2025', rawScore: 72, finalScore: 72, passingScore: 75, status: 'Tidak Lulus', completedAt: '2024-10-08 09:55', durationUsedMinutes: 58 },
  { id: 'res-6', participantId: 'par-6', participantName: 'Aisyah Putri Azzahra', nisn: '0089871234', schoolName: 'SMP Negeri 2 Semarang', className: 'IX A', eventId: 'ev-3', eventTitle: 'Ujian Tengah Semester (PTS) Gasal 2024/2025', rawScore: 91, finalScore: 91, passingScore: 75, status: 'Lulus', completedAt: '2024-10-08 09:30', durationUsedMinutes: 44 },
];

export const mockPermissionTree: PermissionNode[] = [
  {
    id: 'node-dashboard',
    key: 'dashboard',
    label: 'Dashboard Overview',
    path: '/',
  },
  {
    id: 'node-master',
    key: 'master',
    label: 'Master Data',
    children: [
      { id: 'node-master-bobot', key: 'master.config-bobot', label: 'Config Bobot', path: '/master/config-bobot' },
      { id: 'node-master-tapel', key: 'master.tahun-pelajaran', label: 'Tahun Pelajaran', path: '/master/tahun-pelajaran' },
      { id: 'node-master-jenjang', key: 'master.jenjang', label: 'Jenjang', path: '/master/jenjang' },
      { id: 'node-master-tipe-ujian', key: 'master.tipe-ujian', label: 'Tipe Ujian', path: '/master/tipe-ujian' },
      { id: 'node-master-sekolah', key: 'master.sekolah', label: 'Sekolah', path: '/master/sekolah' },
      { id: 'node-master-cabang', key: 'master.cabang', label: 'Cabang', path: '/master/cabang' },
      { id: 'node-master-role', key: 'master.role-user', label: 'Role User', path: '/master/role-user' },
      { id: 'node-master-passing-grade', key: 'master.passing-grade', label: 'Passing Grade', path: '/master/passing-grade' },
      { id: 'node-master-tipe-soal', key: 'master.tipe-soal', label: 'Tipe Soal', path: '/master/tipe-soal' },
      { id: 'node-master-tipe-tes', key: 'master.tipe-tes', label: 'Tipe Tes', path: '/master/tipe-tes' },
    ],
  },
  {
    id: 'node-pegawai',
    key: 'pegawai',
    label: 'Pegawai & Guru',
    path: '/pegawai',
  },
  {
    id: 'node-peserta',
    key: 'peserta',
    label: 'Peserta Ujian',
    path: '/peserta',
  },
  {
    id: 'node-bank-soal',
    key: 'bank-soal',
    label: 'Bank Soal',
    path: '/bank-soal',
  },
  {
    id: 'node-event',
    key: 'event',
    label: 'Event Ujian',
    path: '/event',
  },
  {
    id: 'node-pendaftaran',
    key: 'pendaftaran',
    label: 'Pendaftaran Peserta',
    path: '/pendaftaran',
  },
  {
    id: 'node-soal-event',
    key: 'soal-event',
    label: 'Soal Event (Mapping)',
    path: '/soal-event',
  },
  {
    id: 'node-report',
    key: 'report',
    label: 'Laporan & Analisis',
    path: '/report',
  },
  {
    id: 'node-menu',
    key: 'menu',
    label: 'Menu & RBAC / ACL',
    path: '/menu',
  },
  {
    id: 'node-config',
    key: 'config',
    label: 'Pengaturan Sistem',
    path: '/config',
  },
];

export const initialRoleConfigs: Record<string, RoleConfig> = {
  'role-1': {
    roleId: 'role-1',
    roleCode: 'SUPER_ADMIN',
    roleName: 'Super Administrator',
    scopeType: 'global',
    permissions: {
      'dashboard': { create: true, read: true, update: true, delete: true },
      'master': { create: true, read: true, update: true, delete: true },
      'master.config-bobot': { create: true, read: true, update: true, delete: true },
      'master.tahun-pelajaran': { create: true, read: true, update: true, delete: true },
      'master.jenjang': { create: true, read: true, update: true, delete: true },
      'master.tipe-ujian': { create: true, read: true, update: true, delete: true },
      'master.sekolah': { create: true, read: true, update: true, delete: true },
      'master.cabang': { create: true, read: true, update: true, delete: true },
      'master.role-user': { create: true, read: true, update: true, delete: true },
      'master.passing-grade': { create: true, read: true, update: true, delete: true },
      'master.tipe-soal': { create: true, read: true, update: true, delete: true },
      'master.tipe-tes': { create: true, read: true, update: true, delete: true },
      'pegawai': { create: true, read: true, update: true, delete: true },
      'peserta': { create: true, read: true, update: true, delete: true },
      'bank-soal': { create: true, read: true, update: true, delete: true },
      'event': { create: true, read: true, update: true, delete: true },
      'pendaftaran': { create: true, read: true, update: true, delete: true },
      'soal-event': { create: true, read: true, update: true, delete: true },
      'report': { create: true, read: true, update: true, delete: true },
      'menu': { create: true, read: true, update: true, delete: true },
      'config': { create: true, read: true, update: true, delete: true },
    },
  },
  'role-3': {
    roleId: 'role-3',
    roleCode: 'ADMIN_SEKOLAH',
    roleName: 'Operator / Admin Sekolah',
    scopeType: 'school',
    scopedSchoolId: 'sch-1',
    permissions: {
      'dashboard': { create: false, read: true, update: false, delete: false },
      'master': { create: false, read: true, update: false, delete: false },
      'master.config-bobot': { create: false, read: true, update: false, delete: false },
      'master.tahun-pelajaran': { create: false, read: true, update: false, delete: false },
      'master.jenjang': { create: false, read: true, update: false, delete: false },
      'master.tipe-ujian': { create: false, read: true, update: false, delete: false },
      'master.sekolah': { create: false, read: true, update: true, delete: false },
      'master.cabang': { create: false, read: false, update: false, delete: false },
      'master.role-user': { create: false, read: false, update: false, delete: false },
      'master.passing-grade': { create: false, read: true, update: false, delete: false },
      'master.tipe-soal': { create: false, read: true, update: false, delete: false },
      'master.tipe-tes': { create: false, read: true, update: false, delete: false },
      'pegawai': { create: true, read: true, update: true, delete: false },
      'peserta': { create: true, read: true, update: true, delete: true },
      'bank-soal': { create: true, read: true, update: true, delete: false },
      'event': { create: true, read: true, update: true, delete: false },
      'pendaftaran': { create: true, read: true, update: true, delete: true },
      'soal-event': { create: true, read: true, update: true, delete: false },
      'report': { create: false, read: true, update: false, delete: false },
      'menu': { create: false, read: false, update: false, delete: false },
      'config': { create: false, read: false, update: false, delete: false },
    },
  },
  'role-4': {
    roleId: 'role-4',
    roleCode: 'GURU_PANITIA',
    roleName: 'Guru & Panitia Ujian',
    scopeType: 'school',
    scopedSchoolId: 'sch-1',
    permissions: {
      'dashboard': { create: false, read: true, update: false, delete: false },
      'master': { create: false, read: false, update: false, delete: false },
      'pegawai': { create: false, read: false, update: false, delete: false },
      'peserta': { create: false, read: true, update: false, delete: false },
      'bank-soal': { create: true, read: true, update: true, delete: true },
      'event': { create: false, read: true, update: false, delete: false },
      'pendaftaran': { create: false, read: true, update: false, delete: false },
      'soal-event': { create: true, read: true, update: true, delete: false },
      'report': { create: false, read: true, update: false, delete: false },
      'menu': { create: false, read: false, update: false, delete: false },
      'config': { create: false, read: false, update: false, delete: false },
    },
  },
};

export const defaultAppConfig: AppConfig = {
  appName: 'CBT Admin Enterprise',
  organizationName: 'Badan Pengelola Ujian Digital Nasional',
  logoUrl: '/logo.svg',
  faviconUrl: '/favicon.ico',
  supportEmail: 'bantuan@cbt-admin.id',
  primaryColor: '#ff810a',
  defaultTheme: 'light',
  smtpHost: 'smtp.mailgun.org',
  smtpPort: 587,
  smtpUser: 'admin@cbt-portal.id',
  smtpSenderName: 'Panitia CBT Pusat',
  maintenanceMode: false,
};
